### ISSUE TITLE
run_dialog variant for native dialogs

### ISSUE THREAD

**Issue by piegamesde** [idanarye/woab#34]
`run_dialog` turns out to be incredibly useful, but I just ran into the issue that native dialogues implement other traits. See `FileChooserNative` for example. It would be cool if `run_dialog` supported this as well (maybe `run_native_dialog`?).

**Comment by piegamesde** [comment]
I think using

```rust
ctx.spawn(
			woab::outside(async move {
				(choose.clone(), choose.run())
			})
			.into_actor(self)
			.map(move |result, this, _ctx| {
				todo!()
			})
		);
```

as a workaround is concise enough for this kind of edge case.

**Comment by idanarye** [comment]
No, it is not good enough. The problem with `dialog.run()` is that it blocks the Actix loop, and this still happens when running native dialogs.

**Comment by idanarye** [comment]
OK, I see your point. It turns out that:

1. Native dialogs are not in gtk-rs' default features.
2. [`FileChooserNative`](https://gtk-rs.org/docs/gtk/struct.FileChooserNative.html) is the **only** native dialog.
3. One can always use [`FileChooser`](https://gtk-rs.org/docs/gtk/struct.FileChooser.html) instead.

So yea, fuck it, I'm not incentivized enough to go through the trouble of introducing features to WoAB just to support this. Closing.
